# Generated by Django 4.0.5 on 2022-07-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_readers_alter_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'FINE'), (3, 'GOOD'), (4, 'AMAZING'), (5, 'INCREDIBLE')], null=True),
        ),
    ]
